const iso3_by_name = {
    'Afghanistan': 'AFG',
    'Åland Islands': 'ALA',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'American Samoa': 'ASM',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Anguilla': 'AIA',
    'Antarctica': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Aruba': 'ABW',
    'Australia': 'AUS',
    'Coral Sea Islands': 'AUS', // force-edit
    'Ashmore and Cartier Islands': 'AUS', // force-edit
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas (the)': 'BHS',
    'The Bahamas': 'BHS', // force-edit
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bermuda': 'BMU',
    'Bhutan': 'BTN',
    'Bolivia (Plurinational State of)': 'BOL',
    'Bonaire Sint Eustatius Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'Brazil': 'BRA',
    'British Indian Ocean Territory (the)': 'IOT',
    'British Indian Ocean Territory': 'IOT', // force-edit
    'Brunei Darussalam': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cabo Verde': 'CPV',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cayman Islands (the)': 'CYM',
    'Cayman Islands': 'CYM', // force-edit
    'Central African Republic (the)': 'CAF',
    'Central African Republic': 'CAF', // force-edit
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Paracel Islands': 'CHN', // force-edit
    'Christmas Island': 'CXR',
    'Cocos (Keeling) Islands (the)': 'CCK',
    'Cocos (Keeling) Islands': 'CCK', // force-edit
    'Colombia': 'COL',
    'Comoros (the)': 'COM',
    'Comoros': 'COM', // force-edit
    'Congo (the Democratic Republic of the)': 'COD',
    'Congo DR': 'COD', // force-edit
    'Congo (the)': 'COG',
    'Congo': 'COG', // force-edit
    'Cook Islands (the)': 'COK',
    'Cook Islands': 'COK', // force-edit
    'Costa Rica': 'CRI',
    "Côte d'Ivoire": 'CIV',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Curacao': 'CUW', // force-edit
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic (the)': 'DOM',
    'Dominican Republic': 'DOM', // force-edit
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Falkland Islands (the)': 'FLK',
    'Falkland Islands': 'FLK', // force-edit
    'Faroe Islands (the)': 'FRO',
    'Faroe Islands': 'FRO', // force-edit
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'Clipperton Island': 'FRA', // force-edit
    'French Guiana': 'GUF',
    'French Polynesia': 'PYF',
    'French Southern Territories (the)': 'ATF',
    'French Southern and Antarctic Lands': 'ATF', // force-edit
    'Gabon': 'GAB',
    'Gambia (the)': 'GMB',
    'The Gambia': 'GMB', // force-edit
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'Guam': 'GUM',
    'Guatemala': 'GTM',
    'Guernsey': 'GGY',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Heard Island and McDonald Islands': 'HMD',
    'Holy See (the)': 'VAT',
    'Vatican City (Holy See)': 'VAT', // force-edit
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran (Islamic Republic of)': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Isle of Man': 'IMN',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jersey': 'JEY',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    "Korea (the Democratic People's Republic of)": 'PRK',
    "North Korea": 'PRK', // force-edit
    'Korea (the Republic of)': 'KOR',
    'South Korea': 'KOR', // force-edit
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    "Lao People's Democratic Republic (the)": 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Macao': 'MAC',
    'Macau': 'MAC', // force-edit
    'North Macedonia': 'MKD',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands (the)': 'MHL',
    'Marshall Islands': 'MHL', // force-edit
    'Martinique': 'MTQ',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mayotte': 'MYT',
    'Mexico': 'MEX',
    'Micronesia (Federated States of)': 'FSM',
    'Moldova (the Republic of)': 'MDA',
    'Moldova': 'MDA', // force-edit
    'Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands, Kingdom of the': 'NLD',
    'Netherlands': 'NLD', // force-edit
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger (the)': 'NER',
    'Niger': 'NER', // force-edit
    'Nigeria': 'NGA',
    'Niue': 'NIU',
    'Norfolk Island': 'NFK',
    'Northern Mariana Islands (the)': 'MNP',
    'Northern Mariana Islands': 'MNP', // force-edit
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Palestine, State of': 'PSE',
    'Gaza Strip': 'PSE', // force-edit
    'West Bank': 'PSE', // force-edit
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines (the)': 'PHL',
    'Philippines': 'PHL', // force-edit
    'Pitcairn': 'PCN',
    'Pitcairn Islands': 'PCN', // force-edit
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Puerto Rico': 'PRI',
    'Qatar': 'QAT',
    'Réunion': 'REU',
    'Romania': 'ROU',
    'Russian Federation (the)': 'RUS',
    'Russia': 'RUS', // force-edit
    'Rwanda': 'RWA',
    'Saint Barthélemy': 'BLM',
    'Saint Barthelemy': 'BLM', // force-edit
    'Saint Helena Ascension Island Tristan da Cunha': 'SHN',
    'Saint Helena': 'SHN', // force-edit
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Martin (French part)': 'MAF',
    'Saint Martin': 'MAF', // force-edit
    'Saint Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM',
    'San Marino': 'SMR',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Sint Maarten (Dutch part)': 'SXM',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'South Sudan': 'SSD',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan (the)': 'SDN',
    'Sudan': 'SDN', // force-edit
    'Suriname': 'SUR',
    'Svalbard Jan Mayen': 'SJM',
    'Svalbard': 'SJM', // force-edit
    'Jan Mayen': 'SJM', // force-edit
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syrian Arab Republic (the)': 'SYR',
    'Syria': 'SYR', // force-edit
    'Taiwan (Province of China)': 'TWN',
    'Taiwan': 'TWN', // force-edit
    'Tajikistan': 'TJK',
    'Tanzania, the United Republic of': 'TZA',
    'Tanzania': 'TZA', // force-edit
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tokelau': 'TKL',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Türkiye ': 'TUR',
    'Turkey': 'TUR', // force-edit
    'Turkmenistan': 'TKM',
    'Turks and Caicos Islands (the)': 'TCA',
    'Turks and Caicos Islands': 'TCA', // force-edit
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates (the)': 'ARE',
    'United Arab Emirates': 'ARE', // force-edit
    'United Kingdom of Great Britain and Northern Ireland (the)': 'GBR',
    'United Kingdom': 'GBR', // force-edit
    'Akrotiri (Sovereign Base)': 'GBR', // force-edit
    'Dhekelia (Sovereign Base)': 'GBR', // force-edit
    'United States Minor Outlying Islands (the)': 'UMI',
    'United States of America (the)': 'USA',
    'United States': 'USA', // force-edit
    'US Pacific Island Wildlife Refuges': 'USA',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela (Bolivarian Republic of)': 'VEN',
    'Viet Nam': 'VNM',
    'Virgin Islands (British)': 'VGB',
    'British Virgin Islands': 'VGB', // force-edit
    'Virgin Islands (U.S.)': 'VIR',
    'US Virgin Islands': 'VIR', // force-edit
    'Wallis and Futuna': 'WLF',
    'Western Sahara': 'ESH',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'Kosovo': 'XKX' // temporary EU-issuance
};

const iso3_by_official_name = {
    'The Islamic Republic of Afghanistan': 'AFG',
    'Åland': 'ALA',
    'The Republic of Albania': 'ALB',
    "The People's Democratic Republic of Algeria": 'DZA',
    'The Territory of American Samoa': 'ASM',
    'The Principality of Andorra': 'AND',
    'The Republic of Angola': 'AGO',
    'Anguilla': 'AIA',
    'All land and ice shelves south of the 60th parallel south': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'The Argentine Republic': 'ARG',
    'The Republic of Armenia': 'ARM',
    'Aruba': 'ABW',
    'The Commonwealth of Australia': 'AUS',
    'The Republic of Austria': 'AUT',
    'The Republic of Azerbaijan': 'AZE',
    'The Commonwealth of The Bahamas': 'BHS',
    'The Kingdom of Bahrain': 'BHR',
    "The People's Republic of Bangladesh": 'BGD',
    'Barbados': 'BRB',
    'The Republic of Belarus': 'BLR',
    'The Kingdom of Belgium': 'BEL',
    'Belize': 'BLZ',
    'The Republic of Benin': 'BEN',
    'Bermuda': 'BMU',
    'The Kingdom of Bhutan': 'BTN',
    'The Plurinational State of Bolivia': 'BOL',
    'Bonaire, Sint Eustatius and Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'The Republic of Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'The Federative Republic of Brazil': 'BRA',
    'The British Indian Ocean Territory': 'IOT',
    'The Nation of Brunei, the Abode of Peace': 'BRN',
    'The Republic of Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'The Republic of Burundi': 'BDI',
    'The Republic of Cabo Verde': 'CPV',
    'The Kingdom of Cambodia': 'KHM',
    'The Republic of Cameroon': 'CMR',
    'Canada': 'CAN',
    'The Cayman Islands': 'CYM',
    'The Central African Republic': 'CAF',
    'The Republic of Chad': 'TCD',
    'The Republic of Chile': 'CHL',
    "The People's Republic of China": 'CHN',
    'The Territory of Christmas Island': 'CXR',
    'The Territory of Cocos (Keeling) Islands': 'CCK',
    'The Republic of Colombia': 'COL',
    'The Union of the Comoros': 'COM',
    'The Democratic Republic of the Congo': 'COD',
    'The Republic of the Congo': 'COG',
    'The Cook Islands': 'COK',
    'The Republic of Costa Rica': 'CRI',
    "The Republic of Côte d'Ivoire": 'CIV',
    'The Republic of Croatia': 'HRV',
    'The Republic of Cuba': 'CUB',
    'The Country of Curaçao': 'CUW',
    'The Republic of Cyprus': 'CYP',
    'The Czech Republic': 'CZE',
    'The Kingdom of Denmark': 'DNK',
    'The Republic of Djibouti': 'DJI',
    'The Commonwealth of Dominica': 'DMA',
    'The Dominican Republic': 'DOM',
    'The Republic of Ecuador': 'ECU',
    'The Arab Republic of Egypt': 'EGY',
    'The Republic of El Salvador': 'SLV',
    'The Republic of Equatorial Guinea': 'GNQ',
    'The State of Eritrea': 'ERI',
    'The Republic of Estonia': 'EST',
    'The Kingdom of Eswatini': 'SWZ',
    'The Federal Democratic Republic of Ethiopia': 'ETH',
    'The Falkland Islands': 'FLK',
    'The Faroe Islands': 'FRO',
    'The Republic of Fiji': 'FJI',
    'The Republic of Finland': 'FIN',
    'The French Republic': 'FRA',
    'Guyane': 'GUF',
    'French Polynesia': 'PYF',
    'The French Southern and Antarctic Lands': 'ATF',
    'The Gabonese Republic': 'GAB',
    'The Republic of The Gambia': 'GMB',
    'Georgia': 'GEO',
    'The Federal Republic of Germany': 'DEU',
    'The Republic of Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'The Hellenic Republic': 'GRC',
    'Kalaallit Nunaat': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'The Territory of Guam': 'GUM',
    'The Republic of Guatemala': 'GTM',
    'The Bailiwick of Guernsey': 'GGY',
    'The Republic of Guinea': 'GIN',
    'The Republic of Guinea-Bissau': 'GNB',
    'The Co-operative Republic of Guyana': 'GUY',
    'The Republic of Haiti': 'HTI',
    'The Territory of Heard Island and McDonald Islands': 'HMD',
    'The Holy See': 'VAT',
    'The Republic of Honduras': 'HND',
    'The Hong Kong Special Administrative Region of China': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'The Republic of India': 'IND',
    'The Republic of Indonesia': 'IDN',
    'The Islamic Republic of Iran': 'IRN',
    'The Republic of Iraq': 'IRQ',
    'Ireland': 'IRL',
    'The Isle of Man': 'IMN',
    'The State of Israel': 'ISR',
    'The Italian Republic': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'The Bailiwick of Jersey': 'JEY',
    'The Hashemite Kingdom of Jordan': 'JOR',
    'The Republic of Kazakhstan': 'KAZ',
    'The Republic of Kenya': 'KEN',
    'The Republic of Kiribati': 'KIR',
    "The Democratic People's Republic of Korea": 'PRK',
    'The Republic of Korea': 'KOR',
    'The State of Kuwait': 'KWT',
    'The Kyrgyz Republic': 'KGZ',
    "The Lao People's Democratic Republic": 'LAO',
    'The Republic of Latvia': 'LVA',
    'The Lebanese Republic': 'LBN',
    'The Kingdom of Lesotho': 'LSO',
    'The Republic of Liberia': 'LBR',
    'The State of Libya': 'LBY',
    'The Principality of Liechtenstein': 'LIE',
    'The Republic of Lithuania': 'LTU',
    'The Grand Duchy of Luxembourg': 'LUX',
    'The Macao Special Administrative Region of China': 'MAC',
    'The Republic of North Macedonia': 'MKD',
    'The Republic of Madagascar': 'MDG',
    'The Republic of Malawi': 'MWI',
    'Malaysia': 'MYS',
    'The Republic of Maldives': 'MDV',
    'The Republic of Mali': 'MLI',
    'The Republic of Malta': 'MLT',
    'The Republic of the Marshall Islands': 'MHL',
    'Martinique': 'MTQ',
    'The Islamic Republic of Mauritania': 'MRT',
    'The Republic of Mauritius': 'MUS',
    'The Department of Mayotte': 'MYT',
    'The United Mexican States': 'MEX',
    'The Federated States of Micronesia': 'FSM',
    'The Republic of Moldova': 'MDA',
    'The Principality of Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'The Kingdom of Morocco': 'MAR',
    'The Republic of Mozambique': 'MOZ',
    'The Republic of the Union of Myanmar': 'MMR',
    'The Republic of Namibia': 'NAM',
    'The Republic of Nauru': 'NRU',
    'The Federal Democratic Republic of Nepal': 'NPL',
    'The Kingdom of the Netherlands': 'NLD',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'The Republic of Nicaragua': 'NIC',
    'The Republic of the Niger': 'NER',
    'The Federal Republic of Nigeria': 'NGA',
    'Niue': 'NIU',
    'The Territory of Norfolk Island': 'NFK',
    'The Commonwealth of the Northern Mariana Islands': 'MNP',
    'The Kingdom of Norway': 'NOR',
    'The Sultanate of Oman': 'OMN',
    'The Islamic Republic of Pakistan': 'PAK',
    'The Republic of Palau': 'PLW',
    'The State of Palestine': 'PSE',
    'The Republic of Panamá': 'PAN',
    'The Independent State of Papua New Guinea': 'PNG',
    'The Republic of Paraguay': 'PRY',
    'The Republic of Perú': 'PER',
    'The Republic of the Philippines': 'PHL',
    'The Pitcairn, Henderson, Ducie and Oeno Islands': 'PCN',
    'The Republic of Poland': 'POL',
    'The Portuguese Republic': 'PRT',
    'The Commonwealth of Puerto Rico': 'PRI',
    'The State of Qatar': 'QAT',
    'Réunion': 'REU',
    'Romania': 'ROU',
    'The Russian Federation': 'RUS',
    'The Republic of Rwanda': 'RWA',
    'The Collectivity of Saint-Barthélemy': 'BLM',
    'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'The Collectivity of Saint-Martin': 'MAF',
    'The Overseas Collectivity of Saint-Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'The Independent State of Samoa': 'WSM',
    'The Republic of San Marino': 'SMR',
    'The Democratic Republic of São Tomé and Príncipe': 'STP',
    'The Kingdom of Saudi Arabia': 'SAU',
    'The Republic of Senegal': 'SEN',
    'The Republic of Serbia': 'SRB',
    'The Republic of Seychelles': 'SYC',
    'The Republic of Sierra Leone': 'SLE',
    'The Republic of Singapore': 'SGP',
    'Sint Maarten': 'SXM',
    'The Slovak Republic': 'SVK',
    'The Republic of Slovenia': 'SVN',
    'The Solomon Islands': 'SLB',
    'The Federal Republic of Somalia': 'SOM',
    'The Republic of South Africa': 'ZAF',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'The Republic of South Sudan': 'SSD',
    'The Kingdom of Spain': 'ESP',
    'The Democratic Socialist Republic of Sri Lanka': 'LKA',
    'The Republic of the Sudan': 'SDN',
    'The Republic of Suriname': 'SUR',
    'Svalbard and Jan Mayen': 'SJM',
    'The Kingdom of Sweden': 'SWE',
    'The Swiss Confederation': 'CHE',
    'The Syrian Arab Republic': 'SYR',
    'The Republic of China': 'TWN',
    'The Republic of Tajikistan': 'TJK',
    'The United Republic of Tanzania': 'TZA',
    'The Kingdom of Thailand': 'THA',
    'The Democratic Republic of Timor-Leste': 'TLS',
    'The Togolese Republic': 'TGO',
    'Tokelau': 'TKL',
    'The Kingdom of Tonga': 'TON',
    'The Republic of Trinidad and Tobago': 'TTO',
    'The Republic of Tunisia': 'TUN',
    'The Republic of Türkiye': 'TUR',
    'Turkmenistan': 'TKM',
    'The Turks and Caicos Islands': 'TCA',
    'Tuvalu': 'TUV',
    'The Republic of Uganda': 'UGA',
    'Ukraine': 'UKR',
    'The United Arab Emirates': 'ARE',
    'The United Kingdom of Great Britain and Northern Ireland': 'GBR',
    'Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island': 'UMI',
    'Navassa Island': 'UMI', // force-edit
    'Wake Island': 'UMI', // force-edit
    'The United States of America': 'USA',
    'The Oriental Republic of Uruguay': 'URY',
    'The Republic of Uzbekistan': 'UZB',
    'The Republic of Vanuatu': 'VUT',
    'The Bolivarian Republic of Venezuela': 'VEN',
    'The Socialist Republic of Viet Nam': 'VNM',
    'The Virgin Islands': 'VGB',
    'The Virgin Islands of the United States': 'VIR',
    'The Territory of the Wallis and Futuna Islands': 'WLF',
    'The Sahrawi Arab Democratic Republic': 'ESH',
    'The Republic of Yemen': 'YEM',
    'The Republic of Zambia': 'ZMB',
    'The Republic of Zimbabwe': 'ZWE'
}