const { Pool } = require('pg');

const name_to_code = {
    "Afghanistan": "af", "Albania": "al", "Algeria": "ag", "Andorra": "an", "Angola": "ao",
    "Antigua and Barbuda": "ac", "Argentina": "ar", "Armenia": "am", "Australia": "as", "Austria": "au",
    "Azerbaijan": "aj", "The Bahamas": "bf", "Bahrain": "ba", "Bangladesh": "bg", "Barbados": "bb",
    "Belarus": "bo", "Belgium": "be", "Belize": "bh", "Benin": "bn", "Bhutan": "bt",
    "Bolivia": "bl", "Bosnia and Herzegovina": "bk", "Botswana": "bc", "Brazil": "br", "Brunei": "bx",
    "Bulgaria": "bu", "Burkina Faso": "uv", "Burma": "bm", "Burundi": "by", "Cambodia": "cb",
    "Cameroon": "cm", "Canada": "ca", "Cape Verde": "cv", "Central African Republic": "ct", "Chad": "cd",
    "Chile": "ci", "China": "ch", "Colombia": "co", "Comoros": "cn", "Congo DR": "cf",
    "Congo": "cg", "Costa Rica": "cs", "Cote d'Ivoire": "iv", "Croatia": "hr", "Cuba": "cu",
    "Cyprus": "cy", "Czechia": "ez", "Denmark": "da", "Djibouti": "dj", "Dominica": "do",
    "Dominican Republic": "dr", "Ecuador": "ec", "Egypt": "eg", "El Salvador": "es", "Equatorial Guinea": "ek",
    "Eritrea": "er", "Estonia": "en", "Eswatini": "wz", "Ethiopia": "et", "Fiji": "fj",
    "Finland": "fi", "France": "fr", "Gabon": "gb", "The Gambia": "ga", "Georgia": "gg",
    "Germany": "gm", "Ghana": "gh", "Greece": "gr", "Grenada": "gj", "Guatemala": "gt",
    "Guinea": "gv", "Guinea-Bissau": "pu", "Guyana": "gy", "Haiti": "ha", "Honduras": "ho",
    "Hungary": "hu", "Iceland": "ic", "India": "in", "Indonesia": "id", "Iran": "ir",
    "Iraq": "iz", "Ireland": "ei", "Israel": "is", "Italy": "it", "Jamaica": "jm",
    "Japan": "ja", "Jordan": "jo", "Kazakhstan": "kz", "Kenya": "ke", "Kiribati": "kr",
    "North Korea": "kn", "South Korea": "ks", "Kosovo": "kv", "Kuwait": "ku", "Kyrgyzstan": "kg",
    "Laos": "la", "Latvia": "lg", "Lebanon": "le", "Lesotho": "lt", "Liberia": "li",
    "Libya": "ly", "Liechtenstein": "ls", "Lithuania": "lh", "Luxembourg": "lu", "Madagascar": "ma",
    "Malawi": "mi", "Malaysia": "my", "Maldives": "mv", "Mali": "ml", "Malta": "mt",
    "Marshall Islands": "rm", "Mauritania": "mr", "Mauritius": "mp", "Mexico": "mx", "Micronesia": "fm",
    "Moldova": "md", "Monaco": "mn", "Mongolia": "mg", "Montenegro": "mj", "Morocco": "mo",
    "Mozambique": "mz", "Namibia": "wa", "Nauru": "nr", "Nepal": "np", "Netherlands": "nl",
    "New Zealand": "nz", "Nicaragua": "nu", "Niger": "ng", "Nigeria": "ni", "Norway": "no",
    "North Macedonia": "mk", "Oman": "mu", "Pakistan": "pk", "Palau": "ps", "Panama": "pm",
    "Papua New Guinea": "pp", "Paraguay": "pa", "Peru": "pe", "Philippines": "rp", "Poland": "pl",
    "Portugal": "po", "Qatar": "qa", "Romania": "ro", "Russia": "rs", "Rwanda": "rw",
    "Saint Kitts and Nevis": "sc", "Saint Lucia": "st", "Saint Vincent and the Grenadines": "vc", "Samoa": "ws", "San Marino": "sm",
    "Sao Tome and Principe": "tp", "Saudi Arabia": "sa", "Senegal": "sg", "Serbia": "ri", "Seychelles": "se",
    "Sierra Leone": "sl", "Singapore": "sn", "Slovakia": "lo", "Slovenia": "si", "Solomon Islands": "bp",
    "Somalia": "so", "South Africa": "sf", "South Sudan": "od", "Spain": "sp", "Sri Lanka": "ce",
    "Sudan": "su", "Suriname": "ns", "Sweden": "sw", "Switzerland": "sz", "Syria": "sy",
    "Tajikistan": "ti", "Tanzania": "tz", "Thailand": "th", "Timor-Leste": "tt", "Togo": "to",
    "Tonga": "tn", "Trinidad and Tobago": "td", "Tunisia": "ts", "Turkey": "tu", "Turkmenistan": "tx",
    "Tuvalu": "tv", "Uganda": "ug", "Ukraine": "up", "United Arab Emirates": "ae", "United Kingdom": "uk",
    "United States": "us", "Uruguay": "uy", "Uzbekistan": "uz", "Vanuatu": "nh", "Vatican City (Holy See)": "vt",
    "Venezuela": "ve", "Vietnam": "vm", "Yemen": "ym", "Zambia": "za", "Zimbabwe": "zi",
    // Total 195 countries
    // Plus 65 dependencies
    // Others (3)
    "Taiwan": "tw", "European Union": "ee", "World": "xx",
    // Australia (6)
    "Ashmore and Cartier Islands": "at", "Christmas Island": "kt",
    "Cocos (Keeling) Islands": "ck", "Coral Sea Islands": "cr",
    "Heard Island and McDonald Islands": "hm", "Norfolk Island": "nf",
    // China (2)
    "Hong Kong": "hk", "Macau": "mc",
    // Denmark (2)
    "Faroe Islands": "fo", "Greenland": "gl",
    // France (8)
    "Clipperton Island": "ip", "French Polynesia": "fp",
    "French Southern and Antarctic Lands": "fs", "New Caledonia": "nc",
    "Saint Barthelemy": "tb", "Saint Martin": "rn",
    "Saint Pierre and Miquelon": "sb", "Wallis and Futuna": "wf",
    // Netherlands (3)
    "Aruba": "aa", "Curacao": "uc", "Sint Maarten": "nn",
    // New Zealand (3) 
    "Cook Islands": "cw", "Niue": "ne", "Tokelau": "tl",
    // Norway (3) 
    "Bouvet Island": "bv", "Jan Mayen": "jn", "Svalbard": "sv",
    // United Kingdom (17)
    "Akrotiri (Sovereign Base)": "ax", "Anguilla": "av", "Bermuda": "bd",
    "British Indian Ocean Territory": "io", "British Virgin Islands": "vi", "Cayman Islands": "cj",
    "Dhekelia (Sovereign Base)": "dx", "Falkland Islands": "fk", "Gibraltar": "gi",
    "Guernsey": "gk", "Jersey": "je", "Isle of Man": "im",
    "Montserrat": "mh", "Pitcairn Islands": "pc", "Saint Helena": "sh",
    "South Georgia and the South Sandwich Islands": "sx", "Turks and Caicos Islands": "tk",
    // United States (8)
    "American Samoa": "aq", "Guam": "gq",
    "Navassa Island": "bq", "Northern Mariana Islands": "cq",
    "Puerto Rico": "rq", "US Virgin Islands": "vq",
    "Wake Island": "wq", "US Pacific Island Wildlife Refuges": "um",
    // Miscellaneous (5)
    "Antarctica": "ay",
    "Gaza Strip": "gz",
    "Paracel Islands": "pf",
    "Spratly Islands": "pg",
    "West Bank": "we",
    // Oceans (5)
    "Arctic Ocean": "xq",
    "Atlantic Ocean": "zh",
    "Indian Ocean": "xo",
    "Pacific Ocean": "zn",
    "Southern Ocean": "oo",
    // Plus additions after finding errors (edge-cases of mistmatching names between the EU and the CIA)
    "Aruba (The Netherlands)": "aa",
    "Bahamas": "bf",
    "Bolivia (Plurinational State of)": "bl",
    "Brunei Darussalam": "bx",
    "Cabo Verde": "cv",
    "China - Hong Kong (Special Administrative Region)": "hk",
    "China - Taiwan Province": "tw",
    "Côte d'Ivoire": "iv",
    "Democratic People's Republic of Korea": "kn",
    "Democratic Republic of the Congo": "cf",
    "French Polynesia (France)": "fp",
    "Gambia": "ga",
    "Iran (Islamic Republic of)": "ir",
    "Lao People's Democratic Republic (the)": "la",
    "Micronesia (Federated States of)": "fm",
    "Myanmar": "bm",
    "New Caledonia (France)": "nc",
    "Republic of Korea": "ks",
    "Russian Federation": "rs",
    "Syrian Arab Republic": "sy",
    "Türkiye": "tu",
    "United Kingdom of Great Britain and Northern Ireland": "uk",
    "United Republic of Tanzania": "tz",
    "United States of America": "us",
    "Venezuela (Bolivarian Republic of)": "ve",
    "Viet Nam": "vm",
    "occupied Palestinian territory": "we",
    "the Republic of North Macedonia": "mk",
    // (엣지케이스로 처리해야 할듯) No country code found for Madeira (Portugal)
    // (엣지케이스로 처리해야 할듯) No country code found for Martinique (France)
};

const code_to_continent = {
    ag: 'africa', ao: 'africa', bc: 'africa', bn: 'africa', by: 'africa',
    cd: 'africa', cf: 'africa', cg: 'africa', cm: 'africa', cn: 'africa',
    ct: 'africa', cv: 'africa', dj: 'africa', eg: 'africa', ek: 'africa',
    er: 'africa', et: 'africa', ga: 'africa', gb: 'africa', gh: 'africa',
    gv: 'africa', iv: 'africa', ke: 'africa', li: 'africa', lt: 'africa',
    ly: 'africa', ma: 'africa', mi: 'africa', ml: 'africa', mo: 'africa',
    mp: 'africa', mr: 'africa', mz: 'africa', ng: 'africa', ni: 'africa',
    od: 'africa', pu: 'africa', rw: 'africa', se: 'africa', sf: 'africa',
    sg: 'africa', sh: 'africa', sl: 'africa', so: 'africa', su: 'africa',
    to: 'africa', tp: 'africa', ts: 'africa', tz: 'africa', ug: 'africa',
    uv: 'africa', wa: 'africa', wz: 'africa', za: 'africa', // wi: 'africa' (api deprecated for west sahara)
    zi: 'africa', ay: 'antarctica', bv: 'antarctica', fs: 'antarctica', hm: 'antarctica',
    aq: 'australia-oceania', as: 'australia-oceania', at: 'australia-oceania', bp: 'australia-oceania', ck: 'australia-oceania',
    cq: 'australia-oceania', cr: 'australia-oceania', cw: 'australia-oceania', fj: 'australia-oceania', fm: 'australia-oceania',
    fp: 'australia-oceania', gq: 'australia-oceania', kr: 'australia-oceania', kt: 'australia-oceania', nc: 'australia-oceania',
    ne: 'australia-oceania', nf: 'australia-oceania', nh: 'australia-oceania', nr: 'australia-oceania', nz: 'australia-oceania',
    pc: 'australia-oceania', ps: 'australia-oceania', rm: 'australia-oceania', tl: 'australia-oceania', tn: 'australia-oceania',
    tv: 'australia-oceania', um: 'australia-oceania', wf: 'australia-oceania', wq: 'australia-oceania', ws: 'australia-oceania',
    aa: 'central-america-n-caribbean', ac: 'central-america-n-caribbean', av: 'central-america-n-caribbean', bb: 'central-america-n-caribbean', bf: 'central-america-n-caribbean',
    bh: 'central-america-n-caribbean', bq: 'central-america-n-caribbean', cj: 'central-america-n-caribbean', cs: 'central-america-n-caribbean', cu: 'central-america-n-caribbean',
    do: 'central-america-n-caribbean', dr: 'central-america-n-caribbean', es: 'central-america-n-caribbean', gj: 'central-america-n-caribbean', gt: 'central-america-n-caribbean',
    ha: 'central-america-n-caribbean', ho: 'central-america-n-caribbean', jm: 'central-america-n-caribbean', mh: 'central-america-n-caribbean', nn: 'central-america-n-caribbean',
    nu: 'central-america-n-caribbean', pm: 'central-america-n-caribbean', rn: 'central-america-n-caribbean', rq: 'central-america-n-caribbean', sc: 'central-america-n-caribbean',
    st: 'central-america-n-caribbean', tb: 'central-america-n-caribbean', td: 'central-america-n-caribbean', tk: 'central-america-n-caribbean', uc: 'central-america-n-caribbean',
    vc: 'central-america-n-caribbean', vi: 'central-america-n-caribbean', vq: 'central-america-n-caribbean', kg: 'central-asia', kz: 'central-asia',
    rs: 'central-asia', ti: 'central-asia', tx: 'central-asia', uz: 'central-asia', bm: 'east-n-southeast-asia',
    bx: 'east-n-southeast-asia', cb: 'east-n-southeast-asia', ch: 'east-n-southeast-asia', hk: 'east-n-southeast-asia', id: 'east-n-southeast-asia',
    ja: 'east-n-southeast-asia', kn: 'east-n-southeast-asia', ks: 'east-n-southeast-asia', la: 'east-n-southeast-asia', mc: 'east-n-southeast-asia',
    mg: 'east-n-southeast-asia', my: 'east-n-southeast-asia', pf: 'east-n-southeast-asia', pg: 'east-n-southeast-asia', pp: 'east-n-southeast-asia',
    rp: 'east-n-southeast-asia', sn: 'east-n-southeast-asia', th: 'east-n-southeast-asia', tt: 'east-n-southeast-asia', tw: 'east-n-southeast-asia',
    vm: 'east-n-southeast-asia', al: 'europe', an: 'europe', au: 'europe', ax: 'europe',
    be: 'europe', bk: 'europe', bo: 'europe', bu: 'europe', cy: 'europe',
    da: 'europe', dx: 'europe', ee: 'europe', ei: 'europe', en: 'europe',
    ez: 'europe', fi: 'europe', fo: 'europe', fr: 'europe', gi: 'europe',
    gk: 'europe', gm: 'europe', gr: 'europe', hr: 'europe', hu: 'europe',
    ic: 'europe', im: 'europe', it: 'europe', je: 'europe', jn: 'europe',
    kv: 'europe', lg: 'europe', lh: 'europe', lo: 'europe', ls: 'europe',
    lu: 'europe', md: 'europe', mj: 'europe', mk: 'europe', mn: 'europe',
    mt: 'europe', nl: 'europe', no: 'europe', pl: 'europe', po: 'europe',
    ri: 'europe', ro: 'europe', si: 'europe', sm: 'europe', sp: 'europe',
    sv: 'europe', sw: 'europe', sz: 'europe', uk: 'europe', up: 'europe',
    vt: 'europe', ae: 'middle-east', aj: 'middle-east', am: 'middle-east', ba: 'middle-east',
    gg: 'middle-east', gz: 'middle-east', ir: 'middle-east', is: 'middle-east', iz: 'middle-east',
    jo: 'middle-east', ku: 'middle-east', le: 'middle-east', mu: 'middle-east', qa: 'middle-east',
    sa: 'middle-east', sy: 'middle-east', tu: 'middle-east', we: 'middle-east', ym: 'middle-east',
    bd: 'north-america', ca: 'north-america', gl: 'north-america', ip: 'north-america', mx: 'north-america',
    sb: 'north-america', us: 'north-america', oo: 'oceans', xo: 'oceans', xq: 'oceans',
    zh: 'oceans', zn: 'oceans', ar: 'south-america', bl: 'south-america', br: 'south-america',
    ci: 'south-america', co: 'south-america', ec: 'south-america', fk: 'south-america', gy: 'south-america',
    ns: 'south-america', pa: 'south-america', pe: 'south-america', sx: 'south-america', uy: 'south-america',
    ve: 'south-america', af: 'south-asia', bg: 'south-asia', bt: 'south-asia', ce: 'south-asia',
    in: 'south-asia', io: 'south-asia', mv: 'south-asia', np: 'south-asia', pk: 'south-asia',
    xx: 'world'
};

const rw_edge_cases = {
    "Madeira (Portugal)": "po",
    "Martinique (France)": "fr"
};

const iso3_by_name_edited = {
    'Afghanistan': 'AFG',
    'Åland Islands': 'ALA',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'American Samoa': 'ASM',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Anguilla': 'AIA',
    'Antarctica': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Aruba': 'ABW',
    'Australia': 'AUS',
    'Coral Sea Islands': 'AUS', // force-edit
    'Ashmore and Cartier Islands': 'AUS', // force-edit
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas (the)': 'BHS',
    'The Bahamas': 'BHS', // force-edit
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bermuda': 'BMU',
    'Bhutan': 'BTN',
    'Bolivia (Plurinational State of)': 'BOL',
    'Bonaire Sint Eustatius Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'Brazil': 'BRA',
    'British Indian Ocean Territory (the)': 'IOT',
    'British Indian Ocean Territory': 'IOT', // force-edit
    'Brunei Darussalam': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cabo Verde': 'CPV',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cayman Islands (the)': 'CYM',
    'Cayman Islands': 'CYM', // force-edit
    'Central African Republic (the)': 'CAF',
    'Central African Republic': 'CAF', // force-edit
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Paracel Islands': 'CHN', // force-edit
    'Christmas Island': 'CXR',
    'Cocos (Keeling) Islands (the)': 'CCK',
    'Cocos (Keeling) Islands': 'CCK', // force-edit
    'Colombia': 'COL',
    'Comoros (the)': 'COM',
    'Comoros': 'COM', // force-edit
    'Congo (the Democratic Republic of the)': 'COD',
    'Congo DR': 'COD', // force-edit
    'Congo (the)': 'COG',
    'Congo': 'COG', // force-edit
    'Cook Islands (the)': 'COK',
    'Cook Islands': 'COK', // force-edit
    'Costa Rica': 'CRI',
    "Côte d'Ivoire": 'CIV',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Curacao': 'CUW', // force-edit
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic (the)': 'DOM',
    'Dominican Republic': 'DOM', // force-edit
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Falkland Islands (the)': 'FLK',
    'Falkland Islands': 'FLK', // force-edit
    'Faroe Islands (the)': 'FRO',
    'Faroe Islands': 'FRO', // force-edit
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'Clipperton Island': 'FRA', // force-edit
    'French Guiana': 'GUF',
    'French Polynesia': 'PYF',
    'French Southern Territories (the)': 'ATF',
    'French Southern and Antarctic Lands': 'ATF', // force-edit
    'Gabon': 'GAB',
    'Gambia (the)': 'GMB',
    'The Gambia': 'GMB', // force-edit
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'Guam': 'GUM',
    'Guatemala': 'GTM',
    'Guernsey': 'GGY',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Heard Island and McDonald Islands': 'HMD',
    'Holy See (the)': 'VAT',
    'Vatican City (Holy See)': 'VAT', // force-edit
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran (Islamic Republic of)': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Isle of Man': 'IMN',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jersey': 'JEY',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    "Korea (the Democratic People's Republic of)": 'PRK',
    "North Korea": 'PRK', // force-edit
    'Korea (the Republic of)': 'KOR',
    'South Korea': 'KOR', // force-edit
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    "Lao People's Democratic Republic (the)": 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Macao': 'MAC',
    'Macau': 'MAC', // force-edit
    'North Macedonia': 'MKD',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands (the)': 'MHL',
    'Marshall Islands': 'MHL', // force-edit
    'Martinique': 'MTQ',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mayotte': 'MYT',
    'Mexico': 'MEX',
    'Micronesia (Federated States of)': 'FSM',
    'Moldova (the Republic of)': 'MDA',
    'Moldova': 'MDA', // force-edit
    'Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands, Kingdom of the': 'NLD',
    'Netherlands': 'NLD', // force-edit
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger (the)': 'NER',
    'Niger': 'NER', // force-edit
    'Nigeria': 'NGA',
    'Niue': 'NIU',
    'Norfolk Island': 'NFK',
    'Northern Mariana Islands (the)': 'MNP',
    'Northern Mariana Islands': 'MNP', // force-edit
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Palestine, State of': 'PSE',
    'Gaza Strip': 'PSE', // force-edit
    'West Bank': 'PSE', // force-edit
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines (the)': 'PHL',
    'Philippines': 'PHL', // force-edit
    'Pitcairn': 'PCN',
    'Pitcairn Islands': 'PCN', // force-edit
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Puerto Rico': 'PRI',
    'Qatar': 'QAT',
    'Réunion': 'REU',
    'Romania': 'ROU',
    'Russian Federation (the)': 'RUS',
    'Russia': 'RUS', // force-edit
    'Rwanda': 'RWA',
    'Saint Barthélemy': 'BLM',
    'Saint Barthelemy': 'BLM', // force-edit
    'Saint Helena Ascension Island Tristan da Cunha': 'SHN',
    'Saint Helena': 'SHN', // force-edit
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Martin (French part)': 'MAF',
    'Saint Martin': 'MAF', // force-edit
    'Saint Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM',
    'San Marino': 'SMR',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Sint Maarten (Dutch part)': 'SXM',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'South Sudan': 'SSD',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan (the)': 'SDN',
    'Sudan': 'SDN', // force-edit
    'Suriname': 'SUR',
    'Svalbard Jan Mayen': 'SJM',
    'Svalbard': 'SJM', // force-edit
    'Jan Mayen': 'SJM', // force-edit
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syrian Arab Republic (the)': 'SYR',
    'Syria': 'SYR', // force-edit
    'Taiwan (Province of China)': 'TWN',
    'Taiwan': 'TWN', // force-edit
    'Tajikistan': 'TJK',
    'Tanzania, the United Republic of': 'TZA',
    'Tanzania': 'TZA', // force-edit
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tokelau': 'TKL',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Türkiye ': 'TUR',
    'Turkey': 'TUR', // force-edit
    'Turkmenistan': 'TKM',
    'Turks and Caicos Islands (the)': 'TCA',
    'Turks and Caicos Islands': 'TCA', // force-edit
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates (the)': 'ARE',
    'United Arab Emirates': 'ARE', // force-edit
    'United Kingdom of Great Britain and Northern Ireland (the)': 'GBR',
    'United Kingdom': 'GBR', // force-edit
    'Akrotiri (Sovereign Base)': 'GBR', // force-edit
    'Dhekelia (Sovereign Base)': 'GBR', // force-edit
    'United States Minor Outlying Islands (the)': 'UMI',
    'United States of America (the)': 'USA',
    'United States': 'USA', // force-edit
    'US Pacific Island Wildlife Refuges': 'USA',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela (Bolivarian Republic of)': 'VEN',
    'Viet Nam': 'VNM',
    'Virgin Islands (British)': 'VGB',
    'British Virgin Islands': 'VGB', // force-edit
    'Virgin Islands (U.S.)': 'VIR',
    'US Virgin Islands': 'VIR', // force-edit
    'Wallis and Futuna': 'WLF',
    'Western Sahara': 'ESH',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'Kosovo': 'XKX' // temporary EU-issuance
};

const iso3_by_official_name_edited = {
    'The Islamic Republic of Afghanistan': 'AFG',
    'Åland': 'ALA',
    'The Republic of Albania': 'ALB',
    "The People's Democratic Republic of Algeria": 'DZA',
    'The Territory of American Samoa': 'ASM',
    'The Principality of Andorra': 'AND',
    'The Republic of Angola': 'AGO',
    'Anguilla': 'AIA',
    'All land and ice shelves south of the 60th parallel south': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'The Argentine Republic': 'ARG',
    'The Republic of Armenia': 'ARM',
    'Aruba': 'ABW',
    'The Commonwealth of Australia': 'AUS',
    'The Republic of Austria': 'AUT',
    'The Republic of Azerbaijan': 'AZE',
    'The Commonwealth of The Bahamas': 'BHS',
    'The Kingdom of Bahrain': 'BHR',
    "The People's Republic of Bangladesh": 'BGD',
    'Barbados': 'BRB',
    'The Republic of Belarus': 'BLR',
    'The Kingdom of Belgium': 'BEL',
    'Belize': 'BLZ',
    'The Republic of Benin': 'BEN',
    'Bermuda': 'BMU',
    'The Kingdom of Bhutan': 'BTN',
    'The Plurinational State of Bolivia': 'BOL',
    'Bonaire, Sint Eustatius and Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'The Republic of Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'The Federative Republic of Brazil': 'BRA',
    'The British Indian Ocean Territory': 'IOT',
    'The Nation of Brunei, the Abode of Peace': 'BRN',
    'The Republic of Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'The Republic of Burundi': 'BDI',
    'The Republic of Cabo Verde': 'CPV',
    'The Kingdom of Cambodia': 'KHM',
    'The Republic of Cameroon': 'CMR',
    'Canada': 'CAN',
    'The Cayman Islands': 'CYM',
    'The Central African Republic': 'CAF',
    'The Republic of Chad': 'TCD',
    'The Republic of Chile': 'CHL',
    "The People's Republic of China": 'CHN',
    'The Territory of Christmas Island': 'CXR',
    'The Territory of Cocos (Keeling) Islands': 'CCK',
    'The Republic of Colombia': 'COL',
    'The Union of the Comoros': 'COM',
    'The Democratic Republic of the Congo': 'COD',
    'The Republic of the Congo': 'COG',
    'The Cook Islands': 'COK',
    'The Republic of Costa Rica': 'CRI',
    "The Republic of Côte d'Ivoire": 'CIV',
    'The Republic of Croatia': 'HRV',
    'The Republic of Cuba': 'CUB',
    'The Country of Curaçao': 'CUW',
    'The Republic of Cyprus': 'CYP',
    'The Czech Republic': 'CZE',
    'The Kingdom of Denmark': 'DNK',
    'The Republic of Djibouti': 'DJI',
    'The Commonwealth of Dominica': 'DMA',
    'The Dominican Republic': 'DOM',
    'The Republic of Ecuador': 'ECU',
    'The Arab Republic of Egypt': 'EGY',
    'The Republic of El Salvador': 'SLV',
    'The Republic of Equatorial Guinea': 'GNQ',
    'The State of Eritrea': 'ERI',
    'The Republic of Estonia': 'EST',
    'The Kingdom of Eswatini': 'SWZ',
    'The Federal Democratic Republic of Ethiopia': 'ETH',
    'The Falkland Islands': 'FLK',
    'The Faroe Islands': 'FRO',
    'The Republic of Fiji': 'FJI',
    'The Republic of Finland': 'FIN',
    'The French Republic': 'FRA',
    'Guyane': 'GUF',
    'French Polynesia': 'PYF',
    'The French Southern and Antarctic Lands': 'ATF',
    'The Gabonese Republic': 'GAB',
    'The Republic of The Gambia': 'GMB',
    'Georgia': 'GEO',
    'The Federal Republic of Germany': 'DEU',
    'The Republic of Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'The Hellenic Republic': 'GRC',
    'Kalaallit Nunaat': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'The Territory of Guam': 'GUM',
    'The Republic of Guatemala': 'GTM',
    'The Bailiwick of Guernsey': 'GGY',
    'The Republic of Guinea': 'GIN',
    'The Republic of Guinea-Bissau': 'GNB',
    'The Co-operative Republic of Guyana': 'GUY',
    'The Republic of Haiti': 'HTI',
    'The Territory of Heard Island and McDonald Islands': 'HMD',
    'The Holy See': 'VAT',
    'The Republic of Honduras': 'HND',
    'The Hong Kong Special Administrative Region of China': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'The Republic of India': 'IND',
    'The Republic of Indonesia': 'IDN',
    'The Islamic Republic of Iran': 'IRN',
    'The Republic of Iraq': 'IRQ',
    'Ireland': 'IRL',
    'The Isle of Man': 'IMN',
    'The State of Israel': 'ISR',
    'The Italian Republic': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'The Bailiwick of Jersey': 'JEY',
    'The Hashemite Kingdom of Jordan': 'JOR',
    'The Republic of Kazakhstan': 'KAZ',
    'The Republic of Kenya': 'KEN',
    'The Republic of Kiribati': 'KIR',
    "The Democratic People's Republic of Korea": 'PRK',
    'The Republic of Korea': 'KOR',
    'The State of Kuwait': 'KWT',
    'The Kyrgyz Republic': 'KGZ',
    "The Lao People's Democratic Republic": 'LAO',
    'The Republic of Latvia': 'LVA',
    'The Lebanese Republic': 'LBN',
    'The Kingdom of Lesotho': 'LSO',
    'The Republic of Liberia': 'LBR',
    'The State of Libya': 'LBY',
    'The Principality of Liechtenstein': 'LIE',
    'The Republic of Lithuania': 'LTU',
    'The Grand Duchy of Luxembourg': 'LUX',
    'The Macao Special Administrative Region of China': 'MAC',
    'The Republic of North Macedonia': 'MKD',
    'The Republic of Madagascar': 'MDG',
    'The Republic of Malawi': 'MWI',
    'Malaysia': 'MYS',
    'The Republic of Maldives': 'MDV',
    'The Republic of Mali': 'MLI',
    'The Republic of Malta': 'MLT',
    'The Republic of the Marshall Islands': 'MHL',
    'Martinique': 'MTQ',
    'The Islamic Republic of Mauritania': 'MRT',
    'The Republic of Mauritius': 'MUS',
    'The Department of Mayotte': 'MYT',
    'The United Mexican States': 'MEX',
    'The Federated States of Micronesia': 'FSM',
    'The Republic of Moldova': 'MDA',
    'The Principality of Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'The Kingdom of Morocco': 'MAR',
    'The Republic of Mozambique': 'MOZ',
    'The Republic of the Union of Myanmar': 'MMR',
    'The Republic of Namibia': 'NAM',
    'The Republic of Nauru': 'NRU',
    'The Federal Democratic Republic of Nepal': 'NPL',
    'The Kingdom of the Netherlands': 'NLD',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'The Republic of Nicaragua': 'NIC',
    'The Republic of the Niger': 'NER',
    'The Federal Republic of Nigeria': 'NGA',
    'Niue': 'NIU',
    'The Territory of Norfolk Island': 'NFK',
    'The Commonwealth of the Northern Mariana Islands': 'MNP',
    'The Kingdom of Norway': 'NOR',
    'The Sultanate of Oman': 'OMN',
    'The Islamic Republic of Pakistan': 'PAK',
    'The Republic of Palau': 'PLW',
    'The State of Palestine': 'PSE',
    'The Republic of Panamá': 'PAN',
    'The Independent State of Papua New Guinea': 'PNG',
    'The Republic of Paraguay': 'PRY',
    'The Republic of Perú': 'PER',
    'The Republic of the Philippines': 'PHL',
    'The Pitcairn, Henderson, Ducie and Oeno Islands': 'PCN',
    'The Republic of Poland': 'POL',
    'The Portuguese Republic': 'PRT',
    'The Commonwealth of Puerto Rico': 'PRI',
    'The State of Qatar': 'QAT',
    'Réunion': 'REU',
    'Romania': 'ROU',
    'The Russian Federation': 'RUS',
    'The Republic of Rwanda': 'RWA',
    'The Collectivity of Saint-Barthélemy': 'BLM',
    'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'The Collectivity of Saint-Martin': 'MAF',
    'The Overseas Collectivity of Saint-Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'The Independent State of Samoa': 'WSM',
    'The Republic of San Marino': 'SMR',
    'The Democratic Republic of São Tomé and Príncipe': 'STP',
    'The Kingdom of Saudi Arabia': 'SAU',
    'The Republic of Senegal': 'SEN',
    'The Republic of Serbia': 'SRB',
    'The Republic of Seychelles': 'SYC',
    'The Republic of Sierra Leone': 'SLE',
    'The Republic of Singapore': 'SGP',
    'Sint Maarten': 'SXM',
    'The Slovak Republic': 'SVK',
    'The Republic of Slovenia': 'SVN',
    'The Solomon Islands': 'SLB',
    'The Federal Republic of Somalia': 'SOM',
    'The Republic of South Africa': 'ZAF',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'The Republic of South Sudan': 'SSD',
    'The Kingdom of Spain': 'ESP',
    'The Democratic Socialist Republic of Sri Lanka': 'LKA',
    'The Republic of the Sudan': 'SDN',
    'The Republic of Suriname': 'SUR',
    'Svalbard and Jan Mayen': 'SJM',
    'The Kingdom of Sweden': 'SWE',
    'The Swiss Confederation': 'CHE',
    'The Syrian Arab Republic': 'SYR',
    'The Republic of China': 'TWN',
    'The Republic of Tajikistan': 'TJK',
    'The United Republic of Tanzania': 'TZA',
    'The Kingdom of Thailand': 'THA',
    'The Democratic Republic of Timor-Leste': 'TLS',
    'The Togolese Republic': 'TGO',
    'Tokelau': 'TKL',
    'The Kingdom of Tonga': 'TON',
    'The Republic of Trinidad and Tobago': 'TTO',
    'The Republic of Tunisia': 'TUN',
    'The Republic of Türkiye': 'TUR',
    'Turkmenistan': 'TKM',
    'The Turks and Caicos Islands': 'TCA',
    'Tuvalu': 'TUV',
    'The Republic of Uganda': 'UGA',
    'Ukraine': 'UKR',
    'The United Arab Emirates': 'ARE',
    'The United Kingdom of Great Britain and Northern Ireland': 'GBR',
    'Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island': 'UMI',
    'Navassa Island': 'UMI', // force-edit
    'Wake Island': 'UMI', // force-edit
    'The United States of America': 'USA',
    'The Oriental Republic of Uruguay': 'URY',
    'The Republic of Uzbekistan': 'UZB',
    'The Republic of Vanuatu': 'VUT',
    'The Bolivarian Republic of Venezuela': 'VEN',
    'The Socialist Republic of Viet Nam': 'VNM',
    'The Virgin Islands': 'VGB',
    'The Virgin Islands of the United States': 'VIR',
    'The Territory of the Wallis and Futuna Islands': 'WLF',
    'The Sahrawi Arab Democratic Republic': 'ESH',
    'The Republic of Yemen': 'YEM',
    'The Republic of Zambia': 'ZMB',
    'The Republic of Zimbabwe': 'ZWE'
}

const iso3_by_name = {
    'Afghanistan': 'AFG',
    'Åland Islands': 'ALA',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'American Samoa': 'ASM',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Anguilla': 'AIA',
    'Antarctica': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Aruba': 'ABW',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas (the)': 'BHS',
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bermuda': 'BMU',
    'Bhutan': 'BTN',
    'Bolivia (Plurinational State of)': 'BOL',
    'Bonaire Sint Eustatius Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'Brazil': 'BRA',
    'British Indian Ocean Territory (the)': 'IOT',
    'Brunei Darussalam': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cabo Verde': 'CPV',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cayman Islands (the)': 'CYM',
    'Central African Republic (the)': 'CAF',
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Christmas Island': 'CXR',
    'Cocos (Keeling) Islands (the)': 'CCK',
    'Colombia': 'COL',
    'Comoros (the)': 'COM',
    'Congo (the Democratic Republic of the)': 'COD',
    'Congo (the)': 'COG',
    'Cook Islands (the)': 'COK',
    'Costa Rica': 'CRI',
    "Côte d'Ivoire": 'CIV',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic (the)': 'DOM',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Falkland Islands (the)': 'FLK',
    'Faroe Islands (the)': 'FRO',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'French Guiana': 'GUF',
    'French Polynesia': 'PYF',
    'French Southern Territories (the)': 'ATF',
    'Gabon': 'GAB',
    'Gambia (the)': 'GMB',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'Guam': 'GUM',
    'Guatemala': 'GTM',
    'Guernsey': 'GGY',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Heard Island and McDonald Islands': 'HMD',
    'Holy See (the)': 'VAT',
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran (Islamic Republic of)': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Isle of Man': 'IMN',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jersey': 'JEY',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    "Korea (the Democratic People's Republic of)": 'PRK',
    'Korea (the Republic of)': 'KOR',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    "Lao People's Democratic Republic (the)": 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Macao': 'MAC',
    'North Macedonia': 'MKD',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands (the)': 'MHL',
    'Martinique': 'MTQ',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mayotte': 'MYT',
    'Mexico': 'MEX',
    'Micronesia (Federated States of)': 'FSM',
    'Moldova (the Republic of)': 'MDA',
    'Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands, Kingdom of the': 'NLD',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger (the)': 'NER',
    'Nigeria': 'NGA',
    'Niue': 'NIU',
    'Norfolk Island': 'NFK',
    'Northern Mariana Islands (the)': 'MNP',
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Palestine, State of': 'PSE',
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines (the)': 'PHL',
    'Pitcairn': 'PCN',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Puerto Rico': 'PRI',
    'Qatar': 'QAT',
    'Réunion': 'REU',
    'Romania': 'ROU',
    'Russian Federation (the)': 'RUS',
    'Rwanda': 'RWA',
    'Saint Barthélemy': 'BLM',
    'Saint Helena Ascension Island Tristan da Cunha': 'SHN',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Martin (French part)': 'MAF',
    'Saint Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM',
    'San Marino': 'SMR',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Sint Maarten (Dutch part)': 'SXM',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'South Sudan': 'SSD',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan (the)': 'SDN',
    'Suriname': 'SUR',
    'Svalbard Jan Mayen': 'SJM',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syrian Arab Republic (the)': 'SYR',
    'Taiwan (Province of China)': 'TWN',
    'Tajikistan': 'TJK',
    'Tanzania, the United Republic of': 'TZA',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tokelau': 'TKL',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Türkiye ': 'TUR',
    'Turkmenistan': 'TKM',
    'Turks and Caicos Islands (the)': 'TCA',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates (the)': 'ARE',
    'United Kingdom of Great Britain and Northern Ireland (the)': 'GBR',
    'United States Minor Outlying Islands (the)': 'UMI',
    'United States of America (the)': 'USA',
    'US Pacific Island Wildlife Refuges': 'USA',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela (Bolivarian Republic of)': 'VEN',
    'Viet Nam': 'VNM',
    'Virgin Islands (British)': 'VGB',
    'Virgin Islands (U.S.)': 'VIR',
    'Wallis and Futuna': 'WLF',
    'Western Sahara': 'ESH',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'Kosovo': 'XKX', // No ISO3 yet
};

const iso3_by_official_name = {
    'The Islamic Republic of Afghanistan': 'AFG',
    'Åland': 'ALA',
    'The Republic of Albania': 'ALB',
    "The People's Democratic Republic of Algeria": 'DZA',
    'The Territory of American Samoa': 'ASM',
    'The Principality of Andorra': 'AND',
    'The Republic of Angola': 'AGO',
    'Anguilla': 'AIA',
    'All land and ice shelves south of the 60th parallel south': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'The Argentine Republic': 'ARG',
    'The Republic of Armenia': 'ARM',
    'Aruba': 'ABW',
    'The Commonwealth of Australia': 'AUS',
    'The Republic of Austria': 'AUT',
    'The Republic of Azerbaijan': 'AZE',
    'The Commonwealth of The Bahamas': 'BHS',
    'The Kingdom of Bahrain': 'BHR',
    "The People's Republic of Bangladesh": 'BGD',
    'Barbados': 'BRB',
    'The Republic of Belarus': 'BLR',
    'The Kingdom of Belgium': 'BEL',
    'Belize': 'BLZ',
    'The Republic of Benin': 'BEN',
    'Bermuda': 'BMU',
    'The Kingdom of Bhutan': 'BTN',
    'The Plurinational State of Bolivia': 'BOL',
    'Bonaire, Sint Eustatius and Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'The Republic of Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'The Federative Republic of Brazil': 'BRA',
    'The British Indian Ocean Territory': 'IOT',
    'The Nation of Brunei, the Abode of Peace': 'BRN',
    'The Republic of Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'The Republic of Burundi': 'BDI',
    'The Republic of Cabo Verde': 'CPV',
    'The Kingdom of Cambodia': 'KHM',
    'The Republic of Cameroon': 'CMR',
    'Canada': 'CAN',
    'The Cayman Islands': 'CYM',
    'The Central African Republic': 'CAF',
    'The Republic of Chad': 'TCD',
    'The Republic of Chile': 'CHL',
    "The People's Republic of China": 'CHN',
    'The Territory of Christmas Island': 'CXR',
    'The Territory of Cocos (Keeling) Islands': 'CCK',
    'The Republic of Colombia': 'COL',
    'The Union of the Comoros': 'COM',
    'The Democratic Republic of the Congo': 'COD',
    'The Republic of the Congo': 'COG',
    'The Cook Islands': 'COK',
    'The Republic of Costa Rica': 'CRI',
    "The Republic of Côte d'Ivoire": 'CIV',
    'The Republic of Croatia': 'HRV',
    'The Republic of Cuba': 'CUB',
    'The Country of Curaçao': 'CUW',
    'The Republic of Cyprus': 'CYP',
    'The Czech Republic': 'CZE',
    'The Kingdom of Denmark': 'DNK',
    'The Republic of Djibouti': 'DJI',
    'The Commonwealth of Dominica': 'DMA',
    'The Dominican Republic': 'DOM',
    'The Republic of Ecuador': 'ECU',
    'The Arab Republic of Egypt': 'EGY',
    'The Republic of El Salvador': 'SLV',
    'The Republic of Equatorial Guinea': 'GNQ',
    'The State of Eritrea': 'ERI',
    'The Republic of Estonia': 'EST',
    'The Kingdom of Eswatini': 'SWZ',
    'The Federal Democratic Republic of Ethiopia': 'ETH',
    'The Falkland Islands': 'FLK',
    'The Faroe Islands': 'FRO',
    'The Republic of Fiji': 'FJI',
    'The Republic of Finland': 'FIN',
    'The French Republic': 'FRA',
    'Guyane': 'GUF',
    'French Polynesia': 'PYF',
    'The French Southern and Antarctic Lands': 'ATF',
    'The Gabonese Republic': 'GAB',
    'The Republic of The Gambia': 'GMB',
    'Georgia': 'GEO',
    'The Federal Republic of Germany': 'DEU',
    'The Republic of Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'The Hellenic Republic': 'GRC',
    'Kalaallit Nunaat': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'The Territory of Guam': 'GUM',
    'The Republic of Guatemala': 'GTM',
    'The Bailiwick of Guernsey': 'GGY',
    'The Republic of Guinea': 'GIN',
    'The Republic of Guinea-Bissau': 'GNB',
    'The Co-operative Republic of Guyana': 'GUY',
    'The Republic of Haiti': 'HTI',
    'The Territory of Heard Island and McDonald Islands': 'HMD',
    'The Holy See': 'VAT',
    'The Republic of Honduras': 'HND',
    'The Hong Kong Special Administrative Region of China': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'The Republic of India': 'IND',
    'The Republic of Indonesia': 'IDN',
    'The Islamic Republic of Iran': 'IRN',
    'The Republic of Iraq': 'IRQ',
    'Ireland': 'IRL',
    'The Isle of Man': 'IMN',
    'The State of Israel': 'ISR',
    'The Italian Republic': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'The Bailiwick of Jersey': 'JEY',
    'The Hashemite Kingdom of Jordan': 'JOR',
    'The Republic of Kazakhstan': 'KAZ',
    'The Republic of Kenya': 'KEN',
    'The Republic of Kiribati': 'KIR',
    "The Democratic People's Republic of Korea": 'PRK',
    'The Republic of Korea': 'KOR',
    'The State of Kuwait': 'KWT',
    'The Kyrgyz Republic': 'KGZ',
    "The Lao People's Democratic Republic": 'LAO',
    'The Republic of Latvia': 'LVA',
    'The Lebanese Republic': 'LBN',
    'The Kingdom of Lesotho': 'LSO',
    'The Republic of Liberia': 'LBR',
    'The State of Libya': 'LBY',
    'The Principality of Liechtenstein': 'LIE',
    'The Republic of Lithuania': 'LTU',
    'The Grand Duchy of Luxembourg': 'LUX',
    'The Macao Special Administrative Region of China': 'MAC',
    'The Republic of North Macedonia': 'MKD',
    'The Republic of Madagascar': 'MDG',
    'The Republic of Malawi': 'MWI',
    'Malaysia': 'MYS',
    'The Republic of Maldives': 'MDV',
    'The Republic of Mali': 'MLI',
    'The Republic of Malta': 'MLT',
    'The Republic of the Marshall Islands': 'MHL',
    'Martinique': 'MTQ',
    'The Islamic Republic of Mauritania': 'MRT',
    'The Republic of Mauritius': 'MUS',
    'The Department of Mayotte': 'MYT',
    'The United Mexican States': 'MEX',
    'The Federated States of Micronesia': 'FSM',
    'The Republic of Moldova': 'MDA',
    'The Principality of Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'The Kingdom of Morocco': 'MAR',
    'The Republic of Mozambique': 'MOZ',
    'The Republic of the Union of Myanmar': 'MMR',
    'The Republic of Namibia': 'NAM',
    'The Republic of Nauru': 'NRU',
    'The Federal Democratic Republic of Nepal': 'NPL',
    'The Kingdom of the Netherlands': 'NLD',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'The Republic of Nicaragua': 'NIC',
    'The Republic of the Niger': 'NER',
    'The Federal Republic of Nigeria': 'NGA',
    'Niue': 'NIU',
    'The Territory of Norfolk Island': 'NFK',
    'The Commonwealth of the Northern Mariana Islands': 'MNP',
    'The Kingdom of Norway': 'NOR',
    'The Sultanate of Oman': 'OMN',
    'The Islamic Republic of Pakistan': 'PAK',
    'The Republic of Palau': 'PLW',
    'The State of Palestine': 'PSE',
    'The Republic of Panamá': 'PAN',
    'The Independent State of Papua New Guinea': 'PNG',
    'The Republic of Paraguay': 'PRY',
    'The Republic of Perú': 'PER',
    'The Republic of the Philippines': 'PHL',
    'The Pitcairn, Henderson, Ducie and Oeno Islands': 'PCN',
    'The Republic of Poland': 'POL',
    'The Portuguese Republic': 'PRT',
    'The Commonwealth of Puerto Rico': 'PRI',
    'The State of Qatar': 'QAT',
    'Réunion': 'REU',
    'Romania': 'ROU',
    'The Russian Federation': 'RUS',
    'The Republic of Rwanda': 'RWA',
    'The Collectivity of Saint-Barthélemy': 'BLM',
    'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'The Collectivity of Saint-Martin': 'MAF',
    'The Overseas Collectivity of Saint-Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'The Independent State of Samoa': 'WSM',
    'The Republic of San Marino': 'SMR',
    'The Democratic Republic of São Tomé and Príncipe': 'STP',
    'The Kingdom of Saudi Arabia': 'SAU',
    'The Republic of Senegal': 'SEN',
    'The Republic of Serbia': 'SRB',
    'The Republic of Seychelles': 'SYC',
    'The Republic of Sierra Leone': 'SLE',
    'The Republic of Singapore': 'SGP',
    'Sint Maarten': 'SXM',
    'The Slovak Republic': 'SVK',
    'The Republic of Slovenia': 'SVN',
    'The Solomon Islands': 'SLB',
    'The Federal Republic of Somalia': 'SOM',
    'The Republic of South Africa': 'ZAF',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'The Republic of South Sudan': 'SSD',
    'The Kingdom of Spain': 'ESP',
    'The Democratic Socialist Republic of Sri Lanka': 'LKA',
    'The Republic of the Sudan': 'SDN',
    'The Republic of Suriname': 'SUR',
    'Svalbard and Jan Mayen': 'SJM',
    'The Kingdom of Sweden': 'SWE',
    'The Swiss Confederation': 'CHE',
    'The Syrian Arab Republic': 'SYR',
    'The Republic of China': 'TWN',
    'The Republic of Tajikistan': 'TJK',
    'The United Republic of Tanzania': 'TZA',
    'The Kingdom of Thailand': 'THA',
    'The Democratic Republic of Timor-Leste': 'TLS',
    'The Togolese Republic': 'TGO',
    'Tokelau': 'TKL',
    'The Kingdom of Tonga': 'TON',
    'The Republic of Trinidad and Tobago': 'TTO',
    'The Republic of Tunisia': 'TUN',
    'The Republic of Türkiye': 'TUR',
    'Turkmenistan': 'TKM',
    'The Turks and Caicos Islands': 'TCA',
    'Tuvalu': 'TUV',
    'The Republic of Uganda': 'UGA',
    'Ukraine': 'UKR',
    'The United Arab Emirates': 'ARE',
    'The United Kingdom of Great Britain and Northern Ireland': 'GBR',
    'Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island': 'UMI',
    'The United States of America': 'USA',
    'The Oriental Republic of Uruguay': 'URY',
    'The Republic of Uzbekistan': 'UZB',
    'The Republic of Vanuatu': 'VUT',
    'The Bolivarian Republic of Venezuela': 'VEN',
    'The Socialist Republic of Viet Nam': 'VNM',
    'The Virgin Islands': 'VGB',
    'The Virgin Islands of the United States': 'VIR',
    'The Territory of the Wallis and Futuna Islands': 'WLF',
    'The Sahrawi Arab Democratic Republic': 'ESH',
    'The Republic of Yemen': 'YEM',
    'The Republic of Zambia': 'ZMB',
    'The Republic of Zimbabwe': 'ZWE',
    'The Republic of Kosovo': 'XKX', // No ISO3 yet

}

//!SECTION hozip
// const pool = new Pool({
//     user: 'worldisaster',
//     host: 'worldisaster-database.c1bs1dug29ac.ap-northeast-2.rds.amazonaws.com',
//     database: 'worldisaster_db',
//     password: 'world123',
//     port: 5432,
// });

//!SECTION uuuuj
const pool = new Pool({
    user: 'postgres',
    host: 'worldisaster-rds.c8vecnz23gk6.ap-northeast-2.rds.amazonaws.com',
    port: 5432,
    password: 'postdbwjd',
    database: 'worldisaster-test-db',
    ssl: {
        rejectUnauthorized: false
    }
});

const createTable = async () => {
    const client = await pool.connect();
    try {
        const queryText = `
        CREATE TABLE IF NOT EXISTS country_mappings (
            code VARCHAR(20) PRIMARY KEY,
            iso3 VARCHAR(20) NULL,
            continent VARCHAR(255) NULL,
            cia_name VARCHAR(255) NULL,
            rw_name VARCHAR(255) NULL,
            other_name VARCHAR(255) NULL,
            wiki_name VARCHAR(255) NULL,
            wiki_official VARCHAR(255) NULL
          );
        `;
        await client.query(queryText);
        console.log('Table created successfully');
    } catch (error) {
        console.error('Error creating table:', error);
    } finally {
        client.release();
    }
};

const populateTable = async () => {
    const client = await pool.connect();
    try {
        // Populate code and continent
        for (const [code, continent] of Object.entries(code_to_continent)) {
            const insertQuery = 'INSERT INTO country_mappings (code, continent) VALUES ($1, $2) ON CONFLICT (code) DO NOTHING';
            await client.query(insertQuery, [code, continent]);
        }

        // Populate CIA and RW names
        for (const [name, code] of Object.entries(name_to_code)) {
            // Check if cia_name is already set for the code
            const checkQuery = 'SELECT cia_name FROM country_mappings WHERE code = $1';
            const res = await client.query(checkQuery, [code]);

            if (res.rows.length > 0 && res.rows[0].cia_name) {
                // If cia_name is set, update rw_name
                const updateRWQuery = 'UPDATE country_mappings SET rw_name = $1 WHERE code = $2';
                await client.query(updateRWQuery, [name, code]);
            } else {
                // If cia_name is not set, update cia_name
                const updateQuery = 'UPDATE country_mappings SET cia_name = $1 WHERE code = $2';
                await client.query(updateQuery, [name, code]);
            }
        }

        // Populate iso3 column
        for (const [name, code] of Object.entries(name_to_code)) {
            let iso3 = iso3_by_name_edited[name] || iso3_by_official_name_edited[name];

            if (iso3) {
                const updateISO3Query = 'UPDATE country_mappings SET iso3 = $1 WHERE code = $2';
                await client.query(updateISO3Query, [iso3, code]);
            }
        }

        // Update wiki_name and wiki_official
        for (const [name, iso3] of Object.entries(iso3_by_name)) {
            const updateWikiNameQuery = 'UPDATE country_mappings SET wiki_name = $1 WHERE iso3 = $2';
            await client.query(updateWikiNameQuery, [name, iso3]);
        }
        for (const [officialName, iso3] of Object.entries(iso3_by_official_name)) {
            const updateWikiOfficialQuery = 'UPDATE country_mappings SET wiki_official = $1 WHERE iso3 = $2';
            await client.query(updateWikiOfficialQuery, [officialName, iso3]);
        }

        // Handle edge cases (ignore them)
        // for (const [rwName, placeholderCode] of Object.entries(rw_edge_cases)) {
        //     const insertEdgeCaseQuery = 'INSERT INTO country_mappings (code, rw_name) VALUES ($1, $2) ON CONFLICT (code) DO NOTHING';
        //     await client.query(insertEdgeCaseQuery, [placeholderCode, rwName]);
        // }

        // Handle edge cases (Insert into parent country)
        for (const [edge_name, edge_code] of Object.entries(rw_edge_cases)) {
            const updateEdgeCaseQuery = 'UPDATE country_mappings SET other_name = $1 WHERE code = $2';
            await client.query(updateEdgeCaseQuery, [edge_name, edge_code]);
        }

        console.log('Table populated successfully');
    } catch (error) {
        console.error('Error populating table:', error);
    } finally {
        client.release();
    }
};

const main = async () => {
    await createTable();
    await populateTable();
};

main();